bus_stops = [
    'Karingachira', 'Railway Station', 'Pipeline Junction', 'Ernakulam Medical Centre',
    'KSRTC Bus Station', 'Vyttila', 'Chendamangalam Junction', 'Koonammavu',
    'Namborichante aal', 'Civil Station', 'Vai padi', 'Ravipuram', 'KMK Junction',
    'Cheranelloor Signal', 'Naalam Mile', 'Millupadi', 'Khandakarnan veli', 'Vazhikulangara',
    'Varapuzha', 'Municipal Junction', 'Manjumel Kavala', 'Jose Junction', 'Edappally Junction',
    'Kunnumpuram', 'Petta', 'Champakkara', 'Vytilla Junction', 'Aluva Police Station',
    'Medical Trust Hospital', 'Hill Palace', 'Vadakkekotta', 'Kizhakkambalam', 'Achappan Kavala',
    'Morakkala Church', 'Padathikara', 'FACT Club', 'Harimattam Ambalam', 'Ambalamedu Post Office',
    'Kuzhikkad', 'Chakku Company', 'HOC', 'Cochin Refinery', 'Jwalagiri', 'Kollanpady', 'IOC',
    'Chitrapuzha', 'Vaishali', 'Puthiya Road Bypass Junction', 'Sub Station', 'OEN', 'NAD Kavala',
    'Kunjattukara', 'Chakkaraparambu', 'Nadakkavu', 'Elamkulam Junction', 'North Paravur',
    'Thekke Naaluvazhi', 'Kadavanthra', 'Peruvaaram', 'Cheriyappilly', 'Kadavanthara Junction',
    'Janatha', 'Thirumuppam', 'Kundanoor Junction', 'Puthiyakavu Valavu', 'Valiyakulam',
    'Twenty 20 Nagar', 'Puthankaavu', 'Kaloor Stadium', 'Mathrubhoomi', 'North Railway Station',
    'Maharajas Ground', 'Valanjambalam', 'Padma', 'Shenoys', 'Kacheripadi', 'Kavilnada',
    'Koonammavu Market', 'Sealord', 'Thaikkavu', 'Kesari', 'Poosharipadi', 'Cheriyappilly Valavu',
    'Valluvalli', 'Athaani', 'Kochal', 'Kappela', 'Mesthiripadi', 'Sheddupadi', 'Pournami',
    'Shappupadi', 'Pallipadi', 'Thattampadi', 'Ponevazhi', 'Al Ameen', 'Chalikkavattom',
    'Geethanjali Junction', 'Palarivattam', 'Sree Venkateswara High School', 'Pipeline',
    'Palarivattom', 'Town Hall', 'Manorama Junction', 'Vyttila Devaswom Board', 'Vyttila Junction',
    'Convent', 'Government Hospital', 'Aluva KSRTC', 'Pump Junction', 'Bank Junction', 'Aluva',
    'Karothukuzhi', 'Old Railway', 'Zeenath Junction', 'Choondi', 'Colony Padi', 'Cochin Bank',
    'Ashokapuram', 'Carmel Hospital', 'Andicompany', 'Assisi', 'Power House', 'Model Technical School',
    'Aluva Palace', 'Najath Hospital', 'SNDP Junction', 'Bramasthanam', 'Oberon Mall',
    'Thrippunithura', 'Taluk Hospital', 'Gandhi Square', 'Jayanthi Road Junction', 'Maradu',
    'Pallinada', 'P S Mission Hospital', 'Bund', 'Thykoodam', 'Pallimukku Junction', 'Kannadikadu',
    'Deshabhimani', 'Poothota', 'Punnakaveli', 'South Paravoor', 'Chakkukulam', 'Karaparambu',
    'Colony Triveni', 'Kochu Palli', 'Pathaam Mile', 'Udayamperoor', 'Mankayi Kavala',
    'Udayamperoor Kavala', 'Perumthrikovil', 'Puthiyakavu', 'Choorakkad Junction', 'Kinar',
    'Kannankulangara Junction', 'Kizhakkekotta', 'Kizhakke Kotta Junction', 'Thrippunithura Old Stand',
    'S N Junction', 'Petta East', 'Thykoodam Junction', 'Thykoodam Metro Station', 'Elamkulam',
    'Vijaya Hospital', 'Vinayaka', 'Kumaranasan Junction', 'Kavitha', 'Petta Metro Station',
    'Menakakotta', 'Statue Junction', 'Madam', 'Market Junction', 'RCM Hospital', 'Chathari',
    'Alliance Junction', 'Electricity Shop', 'Manakunnam', 'Ambalamugal Ambalam', 'PDPP', 'ESI',
    'Karimugal', 'Carbon Company', 'Pallimugal', 'Post Office', 'Peringala Junction', 'Ambalapady',
    'Morakkala', 'Pallikkara Health', 'Pallikkara', 'Maavinchuvadu', 'Thamarachal', 'Pazhanganad Hospital',
    'Kappela Pady', 'Shapum Pady', 'North Pazhangad', 'Ashan Pady', 'Pukkattupady', 'Wire Ropes Junction',
    'Ashari Pady', 'Edathala Panchayath', 'Malayil Palli', 'Thaikavu Junction', 'SOS', 'Ettekar Pally',
    'Kaloor', 'Ghandhi Nagar', 'Ernakulam South KSRTC', 'South Railway', 'Gandhi Nagar',
    'Gandhinagar Road Junction', 'Kadavanthra Junction', 'Elamakulam Junction', 'Janatha Bus Stop',
    'Vyttila Hub', 'Vytila Hub', 'O.E.N', 'Thykkoodam Junction', 'Chambakkara', 'Petta East/Skyline',
    'Vadakke Kotta', 'S.N Junction', 'Thripunitura Old Bus Stand', 'Kizhakke Kotta', 'R.C.M Hospital',
    'Karingachira Junction', 'Ayurveda Junction', 'Keshavanpady Bus Stop', 'Thiruvankulam Panchayath',
    'Thiruvankulam Junction', 'St. George Shrine', 'Sasthamughal', 'Panikkarupady', 'Varikoli',
    'Manamthadam', 'Puthencruz', 'Kavumthazham', 'Choondi Police Station', 'Choondy Junction',
    'Ambalappady', 'Pathaam Mile/Vadayampady', 'Puthuppanam', 'Kolenchery College', 'Kolenchery Junction',
    'Kolenchery Medical College Junction', 'Thennika', 'Kidachira', 'Nambiyarpady Junction',
    'Kadamattom Church', 'Peruvamuzhi', 'Peruvammuzhi', 'Perummuzhi', 'Badhanippadi', 'Valakom',
    'Mekkadampu Simhasana Church', 'Mekkadambu Panchayath', 'Kadathy Church', 'Velloorkunnam',
    'Kacherithazham', 'Aramanapadi', 'P. O. Junction', 'Government Hospital - Muvattupuzha',
    'K.S.R.T.C Muvattupuzha Bus Stand', 'Government Hospital Muvattupuzha', 'B.O.C/Nehru Park',
    'Kuriyanmala', 'Badhanipadi', 'Kurisumthotty', 'Paalachuvadu', 'Keshavanpady',
    'East Fort Gate Junction', 'City Traffic Police', 'Thrippunithura Bus Stand',
    'Venkateswara High School', 'Ambili Nagar', 'Janatha Junction', 'Kumaranasan',
    'KSRTC Bus Station Ernakulam']

#[print(i) for i in bus_stops]